version: '3'
services:
  backend:
    image: 'maven:3-jdk-8-alpine'
    volumes:
     - ./projetos_back:/app/
    command: mvn spring-boot:run
    working_dir: /app
    ports:
     - 8080:8080

  frontend:
    image: 'node:lts-alpine'
    volumes:
     - ./projetos_front:/app/
    command: sh -c "npm i && npm start"
    working_dir: /app
    ports:
     - 4200:4200
